---
title: "Daily Assignment 17"
author: "[Stone Shi](https://mycraysh.github.io/StoneGIS/)"
subtitle: 'GEOG 176A'
output:
  html_document:
    theme: journal
---
```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(sf)
library(raster)
library(rgdal)
library(rmapshaper)
library(USAboundaries)
library(elevatr)
library(osmdata)
library(leaflet)
```

```{r, warning = FALSE, message = FALSE}

uscities = readr::read_csv("D:/LifeInUCSB/Study/GEOG176A/week3/assignment10/data/uscities.csv") %>%
  st_as_sf(coords = c("lng", "lat"), crs = 4326) %>%
  filter(city == "Goleta") %>%
  st_transform(5070) %>% 
  st_buffer(5000)
st_bbox(uscities) %>% 
  st_as_sfc() %>%
  st_as_sf()

eleplot = get_elev_raster(uscities, z = 11) %>% 
  crop(uscities) %>%
  plot()

```
```{r, warning = FALSE, message = FALSE}
#Properties
#This Raster shows the elevation change of Goleta.
#The bbox value includes the x and y variables.
#After creating the bbox value, I added a z value to represent the scaling above the plane.
#On the right side of the plot is a legend that shows what color the elevation data is represented in.
```


```{r, warning = FALSE, message = FALSE}
ras = raster("D:/LifeInUCSB/Study/GEOG176A/week3/assignment10/data/goleta-elev.tif")
threshold = function(x) {ifelse(x <= 0 , NA, 1)}
thre_ras = calc(ras, threshold)

isoland = thre_ras * ras

rclass1 = data.frame(min = seq(0,500,100),max =  seq(100,600, 100), lab = c(0:5))
rclass2 = reclassify(isoland, rclass1, lowerTRUE = TRUE)
stac = stack(ras,thre_ras, isoland, rclass2) %>% 
  setNames(c( "elevation","mask","terrain", "topo.bounds"))
plot(stac, col = viridis::viridis(256))
```

#day19
```{r, warning = FALSE, message = FALSE}
bb  = st_bbox(s) %>% 
  st_as_sfc() %>% 
  st_transform(4326)

osm = osmdata::opq(bb) %>% 
  add_osm_feature(key = 'amenity', value = "restaurant") %>% 
  osmdata_sf()
restaurant = osm$osm_points 

elevation = raster::extract(ras, restaurant)
restaurant2 = restaurant %>%
  mutate(elevation = elevation) %>% 
  dplyr::select(osm_id, name, amenity,elevation) %>% 
  dplyr::filter(!is.na(name)) 

leaflet() %>%
  addProviderTiles(providers$CartoDB) %>% 
  addMarkers(data = restaurant2, popup = ~as.character(elevation), label = ~name)
```
